// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: directories/directories.proto

package directories

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Display       string                 `protobuf:"bytes,6,opt,name=display,proto3" json:"display,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Markdown      string                 `protobuf:"bytes,8,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Directories   []*Directory           `protobuf:"bytes,9,rep,name=directories,proto3" json:"directories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_directories_directories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{0}
}

func (x *Directory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Directory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Directory) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Directory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Directory) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Directory) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *Directory) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Directory) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *Directory) GetDirectories() []*Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Markdown      string                 `protobuf:"bytes,4,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_directories_directories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDirectoryRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateDirectoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDirectoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateDirectoryRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type CreateDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *Directory             `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryResponse) Reset() {
	*x = CreateDirectoryResponse{}
	mi := &file_directories_directories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryResponse) ProtoMessage() {}

func (x *CreateDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDirectoryResponse) GetDirectory() *Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

type GetDirectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoriesRequest) Reset() {
	*x = GetDirectoriesRequest{}
	mi := &file_directories_directories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoriesRequest) ProtoMessage() {}

func (x *GetDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{3}
}

type GetDirectoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directories   []*Directory           `protobuf:"bytes,1,rep,name=directories,proto3" json:"directories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoriesResponse) Reset() {
	*x = GetDirectoriesResponse{}
	mi := &file_directories_directories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoriesResponse) ProtoMessage() {}

func (x *GetDirectoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoriesResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoriesResponse) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{4}
}

func (x *GetDirectoriesResponse) GetDirectories() []*Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

type GetDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryRequest) Reset() {
	*x = GetDirectoryRequest{}
	mi := &file_directories_directories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryRequest) ProtoMessage() {}

func (x *GetDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{5}
}

func (x *GetDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *Directory             `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryResponse) Reset() {
	*x = GetDirectoryResponse{}
	mi := &file_directories_directories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryResponse) ProtoMessage() {}

func (x *GetDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{6}
}

func (x *GetDirectoryResponse) GetDirectory() *Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

type UpdateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Display       string                 `protobuf:"bytes,3,opt,name=display,proto3" json:"display,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Markdown      string                 `protobuf:"bytes,5,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDirectoryRequest) Reset() {
	*x = UpdateDirectoryRequest{}
	mi := &file_directories_directories_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDirectoryRequest) ProtoMessage() {}

func (x *UpdateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDirectoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDirectoryRequest) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *UpdateDirectoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateDirectoryRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type UpdateDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *Directory             `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDirectoryResponse) Reset() {
	*x = UpdateDirectoryResponse{}
	mi := &file_directories_directories_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDirectoryResponse) ProtoMessage() {}

func (x *UpdateDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDirectoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDirectoryResponse) GetDirectory() *Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

type DeleteDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirectoryRequest) Reset() {
	*x = DeleteDirectoryRequest{}
	mi := &file_directories_directories_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirectoryRequest) ProtoMessage() {}

func (x *DeleteDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirectoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirectoryResponse) Reset() {
	*x = DeleteDirectoryResponse{}
	mi := &file_directories_directories_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirectoryResponse) ProtoMessage() {}

func (x *DeleteDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directories_directories_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirectoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_directories_directories_proto_rawDescGZIP(), []int{10}
}

var File_directories_directories_proto protoreflect.FileDescriptor

const file_directories_directories_proto_rawDesc = "" +
	"\n" +
	"\x1ddirectories/directories.proto\"\xe3\x01\n" +
	"\tDirectory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\adisplay\x18\x06 \x01(\tR\adisplay\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x1a\n" +
	"\bmarkdown\x18\b \x01(\tR\bmarkdown\x12,\n" +
	"\vdirectories\x18\t \x03(\v2\n" +
	".DirectoryR\vdirectories\"y\n" +
	"\x16CreateDirectoryRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bmarkdown\x18\x04 \x01(\tR\bmarkdown\"C\n" +
	"\x17CreateDirectoryResponse\x12(\n" +
	"\tdirectory\x18\x01 \x01(\v2\n" +
	".DirectoryR\tdirectory\"\x17\n" +
	"\x15GetDirectoriesRequest\"F\n" +
	"\x16GetDirectoriesResponse\x12,\n" +
	"\vdirectories\x18\x01 \x03(\v2\n" +
	".DirectoryR\vdirectories\"%\n" +
	"\x13GetDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x14GetDirectoryResponse\x12(\n" +
	"\tdirectory\x18\x01 \x01(\v2\n" +
	".DirectoryR\tdirectory\"\x86\x01\n" +
	"\x16UpdateDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\adisplay\x18\x03 \x01(\tR\adisplay\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1a\n" +
	"\bmarkdown\x18\x05 \x01(\tR\bmarkdown\"C\n" +
	"\x17UpdateDirectoryResponse\x12(\n" +
	"\tdirectory\x18\x01 \x01(\v2\n" +
	".DirectoryR\tdirectory\"(\n" +
	"\x16DeleteDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteDirectoryResponse2\xe3\x02\n" +
	"\x05Order\x12F\n" +
	"\x0fCreateDirectory\x12\x17.CreateDirectoryRequest\x1a\x18.CreateDirectoryResponse\"\x00\x12C\n" +
	"\x0eGetDirectories\x12\x16.GetDirectoriesRequest\x1a\x17.GetDirectoriesResponse\"\x00\x12=\n" +
	"\fGetDirectory\x12\x14.GetDirectoryRequest\x1a\x15.GetDirectoryResponse\"\x00\x12F\n" +
	"\x0fUpdateDirectory\x12\x17.UpdateDirectoryRequest\x1a\x18.UpdateDirectoryResponse\"\x00\x12F\n" +
	"\x0fDeleteDirectory\x12\x17.DeleteDirectoryRequest\x1a\x18.DeleteDirectoryResponse\"\x00B=Z;github.com/nicholasbraun/nicholasbraun-de-proto/directoriesb\x06proto3"

var (
	file_directories_directories_proto_rawDescOnce sync.Once
	file_directories_directories_proto_rawDescData []byte
)

func file_directories_directories_proto_rawDescGZIP() []byte {
	file_directories_directories_proto_rawDescOnce.Do(func() {
		file_directories_directories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directories_directories_proto_rawDesc), len(file_directories_directories_proto_rawDesc)))
	})
	return file_directories_directories_proto_rawDescData
}

var file_directories_directories_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_directories_directories_proto_goTypes = []any{
	(*Directory)(nil),               // 0: Directory
	(*CreateDirectoryRequest)(nil),  // 1: CreateDirectoryRequest
	(*CreateDirectoryResponse)(nil), // 2: CreateDirectoryResponse
	(*GetDirectoriesRequest)(nil),   // 3: GetDirectoriesRequest
	(*GetDirectoriesResponse)(nil),  // 4: GetDirectoriesResponse
	(*GetDirectoryRequest)(nil),     // 5: GetDirectoryRequest
	(*GetDirectoryResponse)(nil),    // 6: GetDirectoryResponse
	(*UpdateDirectoryRequest)(nil),  // 7: UpdateDirectoryRequest
	(*UpdateDirectoryResponse)(nil), // 8: UpdateDirectoryResponse
	(*DeleteDirectoryRequest)(nil),  // 9: DeleteDirectoryRequest
	(*DeleteDirectoryResponse)(nil), // 10: DeleteDirectoryResponse
}
var file_directories_directories_proto_depIdxs = []int32{
	0,  // 0: Directory.directories:type_name -> Directory
	0,  // 1: CreateDirectoryResponse.directory:type_name -> Directory
	0,  // 2: GetDirectoriesResponse.directories:type_name -> Directory
	0,  // 3: GetDirectoryResponse.directory:type_name -> Directory
	0,  // 4: UpdateDirectoryResponse.directory:type_name -> Directory
	1,  // 5: Order.CreateDirectory:input_type -> CreateDirectoryRequest
	3,  // 6: Order.GetDirectories:input_type -> GetDirectoriesRequest
	5,  // 7: Order.GetDirectory:input_type -> GetDirectoryRequest
	7,  // 8: Order.UpdateDirectory:input_type -> UpdateDirectoryRequest
	9,  // 9: Order.DeleteDirectory:input_type -> DeleteDirectoryRequest
	2,  // 10: Order.CreateDirectory:output_type -> CreateDirectoryResponse
	4,  // 11: Order.GetDirectories:output_type -> GetDirectoriesResponse
	6,  // 12: Order.GetDirectory:output_type -> GetDirectoryResponse
	8,  // 13: Order.UpdateDirectory:output_type -> UpdateDirectoryResponse
	10, // 14: Order.DeleteDirectory:output_type -> DeleteDirectoryResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_directories_directories_proto_init() }
func file_directories_directories_proto_init() {
	if File_directories_directories_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directories_directories_proto_rawDesc), len(file_directories_directories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_directories_directories_proto_goTypes,
		DependencyIndexes: file_directories_directories_proto_depIdxs,
		MessageInfos:      file_directories_directories_proto_msgTypes,
	}.Build()
	File_directories_directories_proto = out.File
	file_directories_directories_proto_goTypes = nil
	file_directories_directories_proto_depIdxs = nil
}
